["pyproject.toml".tool.poetry.group.test.dependencies]
pytest = "^8.3.2"
pytest-asyncio = "^0.24.0"
pytest-cov = "^5.0.0"
pytest-env = "^1.1.3"
pytest-sugar = "^1.0.0"
faker = "^29.0.0"
pytest-lazy-fixture = "^0.6.3"

["pyproject.toml".tool.pytest.ini_options]
testpaths = [
  "tests",
]
python_files = "test*.py"
addopts = "-rsxX -l --tb=short --strict-markers --doctest-modules"
xfail_strict = "true"
