"""empty message

Revision ID: cb701963c9ba
Revises: 
Create Date: 2024-09-22 10:20:41.234397+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb701963c9ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flat', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('walker', sa.Enum('PETR', 'ANTON', name='walkerenum'), nullable=False),
    sa.Column('dog_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dog_breed', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('walk_date', sa.Date(), nullable=False),
    sa.Column('walk_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('walker', 'walk_date', 'walk_time', name='walker_date_time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
